"""
Run to host tensorboard locally.

Ignore all the warnings if you don't have a GPU tensorflow configured.
It should print the address in the terminal (like: http://localhost:6006/).
It collects the data from logs directory. This data is generated by tensorflow during training.
"""


def run_tensorboard():
    """Host tensorboard and wait for it's process to close."""
    import os
    from src.data_process.config_paths import DataPathsManager

    data_paths: DataPathsManager = DataPathsManager()
    os.system(f"tensorboard --logdir={data_paths.training_log_path}")


if __name__ == "__main__":
    run_tensorboard()
